# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Build, Test, and Publish Nuget Package

on:
  push:
    branches: [ "main" ]
    tags: 
      - "v[0-9]+.[0-9]+.[0-9]+(-preview[0-9]+)?"
  release:
     types: [ published ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set Version Variable
      if: ${{ github.ref_type == 'tag' }}
      env:
        TAG: ${{ github.ref_name }}
      run: echo "VERSION=${TAG#v}" >> $GITHUB_ENV
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore src
    - name: Build
      run: dotnet build src --no-restore
    - name: Test
      run: dotnet test src --no-build --verbosity normal
    - name: Pack
      if: github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')
      run: dotnet pack src/Pipeware/Pipeware.csproj --output nupkgs /p:PackageVersion=$VERSION
    - name: Upload
      if: github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')
      run: dotnet nuget push nupkgs/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
